# Generated by Django 5.1.1 on 2024-10-30 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('term', models.CharField(max_length=10)),
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('teacher', models.CharField(max_length=100)),
                ('lecture_schedule', models.CharField(max_length=100)),
            ],
        ),
    ]
